### ISSUE TITLE
How to extract messages from RunAbleThread to monobehaviour?

### ISSUE THREAD

**Issue by Kasidit0052** [off99555/Unity3D-Python-Communication#13]
First, Thank you for your amazing repository. UnfortunateIy, I have a difficult time extracting the data from your RunAbleThread to my monobehaviour. This might be a simple question but could you please elaborate the solution? 

thank you

**Comment by offchan42** [comment]
Generally, when you want to communicate messages between 2 threads you will need to use a queue data structure or a callback event. This applies to all programming languages.
For simplicity, add a Queue field inside `HelloRequester` which you use to store messages that you got from ZeroMQ. Then in your `MonoBehaviour`'s `Update()` loop, you check whether the queue is empty. If the queue is not empty then you pop the message from it and process the message according to your game logic.
You will know what to do with your custom `RunAbleThread` implementations after you have done this simple experiment.

Another thing you can do is to write a callback function that is called whenever a message is received. This is more immediate but you probably won't need this speed if you want to do graphics related stuff e.g. changing position of a cube in the game. If the cube is updating its position 10,000 times a second it won't do any good as the `Update()` frequency is only 60 to 90 Hz.
