### ISSUE TITLE
Unity-Python communication (the python client is running in the browser)

### ISSUE THREAD

**Issue by Vishav3** [off99555/Unity3D-Python-Communication#16]
I tried this code and it is working well for unity-python communication when I ran both on my local machine. But since i need to run python in browser and send audio files to unity. Does this code work for that?

**Comment by offchan42** [comment]
That's a general question about ZeroMQ. The code works to show you the example how to send a text to Unity but there's nothing preventing you to extend it to work with images, audio, or arbitrary blob of data.
Just encode your audio file as a binary string and send it, then decode back to audio in unity.

**Comment by Vishav3** [comment]
Thanks for the response! I think the question was not clearly deliver to you. The issue was not about type of data. The issue is that i need to run python code in web browser (using Jupyter notebook). But i am not able to send data from browser to unity. Please give some guidance on that.
