### ISSUE TITLE
[Question] Can this be run in game?

### ISSUE THREAD

**Issue by sweatyc** [off99555/Unity3D-Python-Communication#2]
We are looking for a in-game Python interpreter, so player can code Python in game.

We came across in this great repo and would like to know if this can be used in game, instead of using an external terminal to communicate...?

Or in this case IronPython is enough for me? (I havn't dig deep into IronPython yet...)

**Comment by offchan42** [comment]
@sweatyc This can be run in-game for sure. There are multiple solutions that you can try.
I would try to call the python file in Unity using `ProcessStartInfo` like this: https://answers.unity.com/questions/1127023/running-command-line-action-through-c-script.html

Or ship an `exe` file that first launches python program and then launches the game.

For people that do not have python, you can ship the game with python folder. Or you can just ask them to install python. (I would suggest shipping python with the game to avoid compatibility issue)

For IronPython, you can use this plugin for Unity: https://github.com/exodrifter/unity-python
But beware that it is hard to install a new python library (or maybe not possible).

**Comment by offchan42** [comment]
I forgot to see that you mention "coding in the game".
To code in the game, there is no new specialty there. There is a function `exec` in python that can execute python code from a string.
https://stackoverflow.com/questions/701802/how-do-i-execute-a-string-containing-python-code-in-python
It means you can use either this repo or IronPython to do it.
This repo only serves you as a mean for sending data to python. Whatever you send to python, that's up to you.

**Comment by sweatyc** [comment]
Thx for the reply, I will give it a try!
