### ISSUE TITLE
Communication stops

### ISSUE THREAD

**Issue by RossMelbourne** [off99555/Unity3D-Python-Communication#24]
I have downloaded and opened the Unity project in Unity 2020.3.27f1 and run server.py.  It works as is and stops at 10 message sent and received.  When I modify the code HelloRequester.cs to run continuously the process stops at 30.  Every time.  It stops here:

gotMessage = client.TryReceiveFrameString(out message);  
if (gotMessage) break; // gotMessage is always false after 30 messages.

The strange thing is I can stop and play Unity again and the messages start sending/receiving again - unit 30.  I have tired reducing the delay in the python code and the number of messages goes up but they still stop consistently at the same time each time.

Any ideas on how to get around this?

**Comment by offchan42** [comment]
Not sure why that would cause a problem. Have you tried using the original code and only modifying the number from 10 to 30 or 50 or something like that?
I would suggest to do that first to confirm that there is definitely something special about 30.
https://github.com/off99555/Unity3D-Python-Communication/blob/dfb1c26538c83a7c65cf93611a772661d495c2e8/UnityProject/Assets/NetMQExample/Scripts/HelloRequester.cs#L24

Another recommendation is that if you are looking for a system that you can use in production, maybe you should try SocketIO approach using either SocketIO plugin or BestHTTP plugin.

**Comment by RossMelbourne** [comment]
I did try the original code with line 24 increased from 10 to 50 as suggested with the same result.  Thanks for your suggestion, I will look for alternatives.  It appears NetMQ is no longer a valid solution for Unity.

**Comment by offchan42** [comment]
Yeah, SocketIO works OK from what I tested last year. I used it to stream data at 60 FPS. You can build the project and it still works.
