### ISSUE TITLE
Ask for a version for Linux, thanks

### ISSUE THREAD

**Issue by xdk2023** [off99555/Unity3D-Python-Communication#25]
Hello, author. I would like to ask for a version for Linux. I am a newbie to Unity. I am currently making a small game that I hope to link with a robotic arm. I have encountered a problem with information transmission between Python and Unity. I hope to try your method. Looking forward to your reply.

**Comment by offchan42** [comment]
Thanks for your interest in using this code. But the project is already unmaintained. I suggest you try using network methods developed by this guy: https://assetstore.unity.com/publishers/4137
