### ISSUE TITLE
Python to Unity

### ISSUE THREAD

**Issue by lisa676** [off99555/Unity3D-Python-Communication#4]
Hi @off99555  thanks for this cool stuff. 
I just test your example and it is working fine. I want to ask that, I'm running [this github project](https://github.com/mohitwildbeast/Driver-Drowsiness-Detector) which is in Python. My teacher asked me to transfer all the python code to C++ to run it in Unity. 
So my question is that using your stuff can I directly run python code to Unity and how we can build dll files directly from Python?

**Comment by offchan42** [comment]
You cannot build dll file from python but you can build pyc file which can
be used the same way as py file.
You have to run the python server in command prompt and run unity to query
the the result from python. You can set up a bat file that will run python
server with one click.

**Comment by lisa676** [comment]
Thanks for your quick response. Can you share some more information about pyc file that how I can build pyc? 

Thanks for your kind support

**Comment by offchan42** [comment]
Google "python compile pyc"

**Comment by lisa676** [comment]
Sure, let me have a try. 
One more question. After getting pyc file, will it be able to transfer to Unity using pyc file same as dll using python server as you suggested above.

**Comment by offchan42** [comment]
pyc file has the same behavior as normal py. Whatever you can do with py you will do with pyc. The only difference is that pyc is not-readable. It's not a text file. So it's better than you ship your source code to the user. If you don't care about user modifying/reading your code then you don't need to generate this pyc file.
