### ISSUE TITLE
'Lazy Pirate' Reliability pattern

### ISSUE THREAD

**Issue by jBachalo** [off99555/Unity3D-Python-Communication#8]
Hi
Trying to implement the 'Lazy Pirate' Reliability pattern in the Unity client.
Any chance this has been implemented somewhere?
http://zguide.zeromq.org/cs:lpclient

**Comment by offchan42** [comment]
This repo only provides the basic usage of ZeroMQ. If you want to use the advanced pattern you can definitely use it if you know how to implement it.
